# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19ZqDvVq_kG9XN7orjtr33OvjKuzaBQfF
"""


import streamlit as st
import pickle
import numpy as np

import pickle

with open("my_model.pkl", "rb") as f:
    model = pickle.load(f)

# App Title
st.title("🚢 Titanic Survival Prediction (Logistic Regression)")
st.write("Enter the passenger details below to predict survival.")

st.markdown("---")

# Two-column layout for better UI design
col1, col2 = st.columns(2)

with col1:
    Pclass = st.selectbox("Passenger Class (Pclass)", [1, 2, 3])
    Sex = st.selectbox("Sex (0 = Female, 1 = Male)", [0, 1])
    Age = st.number_input("Age (Standardized Value)", value=0.0, format="%.4f")

with col2:
    SibSp = st.number_input("Number of Siblings/Spouse (SibSp)", value=0)
    Fare = st.number_input("Fare (Standardized Value)", value=0.0, format="%.4f")
    Embarked_S = st.selectbox("Embarked from S (1 = Yes, 0 = No)", [0, 1])
    Tickets = st.number_input("Ticket Number (Standardized Value)", value=0.0, format="%.4f")

st.markdown("---")

# Prediction button
if st.button("Predict Survival"):
    input_data = np.array([[Pclass, Sex, Age, SibSp, Fare, Embarked_S, Tickets]])
    prediction = model.predict(input_data)[0]

    if prediction == 1:
        st.success("🟩 **The passenger is predicted to SURVIVE.**")
    else:
        st.error("🟥 **The passenger is predicted NOT to survive.**")

